<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNNxagFJ\srcIsfett_PhpAnalyzer_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNNxagFJ/srcIsfett_PhpAnalyzer_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerNNxagFJ.legacy');

    return;
}

if (!\class_exists(srcIsfett_PhpAnalyzer_KernelProdContainer::class, false)) {
    \class_alias(\ContainerNNxagFJ\srcIsfett_PhpAnalyzer_KernelProdContainer::class, srcIsfett_PhpAnalyzer_KernelProdContainer::class, false);
}

return new \ContainerNNxagFJ\srcIsfett_PhpAnalyzer_KernelProdContainer([
    'container.build_hash' => 'NNxagFJ',
    'container.build_id' => '154ad17a',
    'container.build_time' => 1564695000,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNNxagFJ');
