<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDLu8FSW\srcIsfett_PhpAnalyzer_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDLu8FSW/srcIsfett_PhpAnalyzer_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerDLu8FSW.legacy');

    return;
}

if (!\class_exists(srcIsfett_PhpAnalyzer_KernelProdContainer::class, false)) {
    \class_alias(\ContainerDLu8FSW\srcIsfett_PhpAnalyzer_KernelProdContainer::class, srcIsfett_PhpAnalyzer_KernelProdContainer::class, false);
}

return new \ContainerDLu8FSW\srcIsfett_PhpAnalyzer_KernelProdContainer([
    'container.build_hash' => 'DLu8FSW',
    'container.build_id' => '92e0c592',
    'container.build_time' => 1564591103,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDLu8FSW');
