<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Isfett\PhpAnalyzer\Console\Application' shared autowired service.

$this->services['Isfett\\PhpAnalyzer\\Console\\Application'] = $instance = new \Isfett\PhpAnalyzer\Console\Application();

$instance->add(new \Isfett\PhpAnalyzer\Console\Command\MostUsedConditionsCommand(new \Isfett\PhpAnalyzer\Builder\FinderBuilder(), new \Isfett\PhpAnalyzer\Builder\ConditionListBuilder(), new \Isfett\PhpAnalyzer\Builder\VisitorBuilder(), new \Isfett\PhpAnalyzer\Builder\ProcessorBuilder(), new \Isfett\PhpAnalyzer\Node\ProcessorRunner(), new \Isfett\PhpAnalyzer\Node\Representation()));

return $instance;
